export {default as Home} from './home/Home'
export {default as Users} from './users/Users'
export {default as Products} from './products/Products'
export {default as Single} from './single/Single'
export {default as New} from './new/New'
export {default as Login} from './login/Login'